### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by varjmes** [dinosaurjs/dinosaurjs.github.io#1]
Hi! Congrats on the new event :)

Just wanted to let you know that the JS Conf Code of Conduct has been updated, to include rad things like 'gender identity and expression' 'age' and more. http://jsconf.com/codeofconduct.html

Not sure if you're accepting PRs so thought I'd just log it here.

Have a great day! :sparkles:

**Comment by stevekinney** [comment]
So sorry that I missed this until now. I'll be sure to update it immediately!
